ecommerce/ecommerce/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'products.views.home', name='home'),
    url(r'^s/$', 'products.views.search', name='search'),
    url(r'^products/$', 'products.views.all', name='products'),
    url(r'^products/(?P<slug>[\w-]+)/$', 'products.views.single', name='single_product'),
    url(r'^cart/(?P<id>\d+)/$', 'carts.views.remove_from_cart', name='remove_from_cart'),
    url(r'^cart/(?P<slug>[\w-]+)/$', 'carts.views.add_to_cart', name='add_to_cart'),
    url(r'^cart/$', 'carts.views.view', name='cart'),
    url(r'^checkout/$', 'orders.views.checkout', name='checkout'),
    url(r'^orders/$', 'orders.views.orders', name='user_orders'),
    url(r'^ajax/dismiss_marketing_message/$', 'marketing.views.dismiss_marketing_message', name='dismiss_marketing_message'),
    url(r'^ajax/email_signup/$', 'marketing.views.email_signup', name='ajax_email_signup'),
    url(r'^ajax/add_user_address/$', 'accounts.views.add_user_address', name='ajax_add_user_address'),

    # url(r'^blog/', include('blog.urls')),
    #(?P<all_items>.*)
    #(?P<id>\d+)
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/logout/$', 'accounts.views.logout_view', name='auth_logout'),
    url(r'^accounts/login/$', 'accounts.views.login_view', name='auth_login'),
    url(r'^accounts/register/$', 'accounts.views.registration_view', name='auth_register'),
    url(r'^accounts/address/add/$', 'accounts.views.add_user_address', name='add_user_address'),
    url(r'^accounts/activate/(?P<activation_key>\w+)/$', 'accounts.views.activation_view', name='activation_view'),
) 


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/accounts/forms.py
from django import forms

from django.contrib.auth import get_user_model



User = get_user_model()

from .models import UserAddress


class UserAddressForm(forms.ModelForm):
	default = forms.BooleanField(label='Make Default')
	class Meta:
		model = UserAddress
		fields = ["address", 
				"address2", 
				"city", 
				"state", 
				"country",
				"zipcode", 
				"phone"]



class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField(widget=forms.PasswordInput())

	def clean_username(self):
		username = self.cleaned_data.get("username")
		try:
			user = User.objects.get(username=username)
		except User.DoesNotExist:
			raise forms.ValidationError("Are you sure you are registered? We cannot find this user.")
		return username

	def clean_password(self):
		username = self.cleaned_data.get("username")
		password = self.cleaned_data.get("password")
		try:
			user = User.objects.get(username=username)
		except:
			user = None
		if user is not None and not user.check_password(password):
			raise forms.ValidationError("Invalid Password")
		elif user is None:
			pass
		else:
			return password


class RegistrationForm(forms.ModelForm):
	email = forms.EmailField(label='Your Email')
	password1 = forms.CharField(label='Password', \
					widget=forms.PasswordInput())
	password2 = forms.CharField(label='Password Confirmation', \
					widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ['username', 'email']

	def clean_password2(self):
		password1 = self.cleaned_data.get('password1')
		password2 = self.cleaned_data.get('password2')
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords do not match")
		return password2

	def clean_email(self):
		email = self.cleaned_data.get("email")
		user_count = User.objects.filter(email=email).count()
		if user_count > 0:
			raise forms.ValidationError("This email has already been registered. Please check and try again or reset your password.")
		return email


	def save(self, commit=True):
		user = super(RegistrationForm, self).save(commit=False)
		user.set_password(self.cleaned_data['password1']) 
		if commit:
			user.save()
		return user

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block head_title %}{% endblock %}CFE STORE</title>

    {% load staticfiles %}
    <!-- <link rel='stylesheet' href='{% static "css/bootstrap.min.css" %}' />
    <link rel='stylesheet' href='{% static "css/bootstrap-theme.min.css" %}' /> -->

      <!-- Latest compiled and minified CSS 
  --> 
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">


	<!-- Optional theme 
 -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap-theme.min.css">
    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/navbar-static-top/navbar-static-top.css" rel="stylesheet">
    <style>
    .alert-top-message {
        margin-bottom: 0px;
        border-radius: 0px;
        text-align: center;
        background-color: #DBDBDB;
     
    }
    .alert-top-message h3{
        margin: 0 auto;
    }

    .modal-dialog {
      margin-top: 15%;
    }
    {% block styles %}
    {% endblock %}

    .background_img_thumb {
        width:100%; 
        height:100%;
        background-image: url("{% static 'img/placeholder.svg' %}");
        background-size:cover;
        background-repeat:no-repeat; 
        background-position:center;
    }


    </style>

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="http://getbootstrap.com/assets/js/ie-emulation-modes-warning.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  </head>

  <body>
  {% if request.session.marketing_message %}
  <div class='alert alert-top-message alert-dismissible' role='alert'>
    <button id='marketing-message-btn' type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <div class="container">
        <h3>{{ request.session.marketing_message|safe }}</h3>
      </div>
  </div>
  {% endif %}

  {% include 'navbar.html' %}

    {% block jumbotron %}
    {% endblock %}

  


    <div class="container">
         {% if messages %}
            {% for message in messages %}
            <div class='alert {% if "success" in message.tags %}alert-success{% elif "warning" in message.tags%}alert-warning{% elif "error" in message.tags %}alert-danger{% endif %} alert-dismissible' role='alert'>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
               
                {% if "safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}
                
          </div>
          {% endfor %}
      {% endif %}
    {% block content %}

    {% endblock %}

    </div> <!-- /container -->

    {% include "modal.html" %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <!-- Latest compiled and minified JavaScript -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script>
      $(document).ready(function(){
        $("#marketing-message-btn").click(function(){
         $.ajax({
              type: "POST",
              url: "{% url 'dismiss_marketing_message' %}",
              data: {
                "dimiss-marketing": true,
                "csrfmiddlewaretoken": "{{ csrf_token }}",
              },
              success: function(data){
              },
              error: function(){
                alert("Error! Something wrong. Please try again later")
              },
           });
        });
    
        {% if not request.user.is_authenticated and not request.session.email_added_marketing and not "accounts" in request.get_full_path %}
        function showModal(){
          $("#marketingModal").modal("show");
          // setTimeout(showModal, 5000);
        }
        // showModal()
        setTimeout(showModal, 5000);
        $("#sendMarketingForm").click(function(e){
          e.preventDefault()
          var mForm = $("#sendForm").serialize()
         $.ajax({
              type: "POST",
              url: "{% url 'ajax_email_signup' %}",
              data: mForm,
              success: function(data){
                // console.log(data)
                $("#modalMessage").html("<p>" + data + "</p>")
                 $("#marketingModal").modal("hide");
              },
              error: function(data){
                // console.log(data)
                // console.log(data.responseJSON)
                var obj = data.responseJSON
                // console.log(obj)
                // console.log(obj.email)
                $("#modalMessage").html("<p style='color:red;'>" + obj.email + "</p>")
              },
           });
        });
        {% endif %}


        

    });


  </script>


	<script>
	$(document).ready(function(){
		{% block jquery %}{% endblock%}
	});

	</script>
  </body>
</html>

ecommerce/templates/form.html
{% extends "base.html" %}



{% block content %}

<div class='col-sm-6 col-sm-offset-3' style='margin-top: 50px;'>
<h1>{{ form_title }}</h1>
<form method='POST' action=''>{% csrf_token %}
{{ form.as_p }}


<input type='submit' value='{% if submit_btn %}{{ submit_btn }}{% else %}Submit{% endif %}' class='btn btn-default' />
</form>
</div>

{% endblock %}

ecommerce/templates/modal.html
<div class="modal fade" id='marketingModal'>
<form method='POST' action='{% url "ajax_email_signup" %}' id='sendForm'>{% csrf_token %} 
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <!-- <input class='form-control' type='text' placeholder='Enter Email' /> -->
        <p id='modalMessage'></p>
        <input id="id_email" class='form-control' maxlength="200" name="email" type="email" placeholder="Your Email">
        
        
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <input type='submit' class='btn btn-success' id='sendMarketingForm'/>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
  </form>
</div><!-- /.modal -->

ecommerce/templates/navbar.html
  <!-- Static navbar -->
    <div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">CFE eCommerce</a>
        </div>
        <div class="navbar-collapse collapse">

          <form class="navbar-form navbar-left" role="search" action='/s/'>
            <div class="form-group">
          <input type="text" class="form-control" name='q' placeholder="Search Product Title">
            </div>
          <button type="submit" class="btn btn-default">Submit</button>
          </form>
          <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'products' %}">Products</a></li>
            <li><a href="{% url 'cart' %}">Cart <span class="badge">{% if not request.session.items_total %} 0 {% else %} {{ request.session.items_total }} {% endif%}</span></a></li>
            {% if user.is_authenticated %}
            <li><a href="#">Account</a></li>
            <li><a href="{% url 'auth_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'auth_login' %}">Login</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>